"""empty message

Revision ID: 052a785664cf
Revises: 73bf1e46f510
Create Date: 2024-12-06 15:44:59.209568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '052a785664cf'
down_revision = '73bf1e46f510'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_earnings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('storyteller_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['storyteller_id'], ['storyteller.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    with op.batch_alter_table('storyteller', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paystack_subaccount_code', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('storyteller', schema=None) as batch_op:
        batch_op.drop_column('paystack_subaccount_code')

    op.drop_table('payment_record')
    op.drop_table('platform_earnings')
    # ### end Alembic commands ###
