"""empty message

Revision ID: 0c7c0eec4a0b
Revises: db1f5a140993
Create Date: 2024-12-02 19:13:12.384070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c7c0eec4a0b'
down_revision = 'db1f5a140993'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('blue_tick', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('blue_tick')

    # ### end Alembic commands ###
