"""empty message

Revision ID: 161a9cd0a80c
Revises: b7b101c0b1b6
Create Date: 2024-11-27 15:52:44.501138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '161a9cd0a80c'
down_revision = 'b7b101c0b1b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visits', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('visits')

    # ### end Alembic commands ###
