"""empty message

Revision ID: 235467bdc446
Revises: c8c9eab3ea12
Create Date: 2024-12-05 05:38:22.536437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '235467bdc446'
down_revision = 'c8c9eab3ea12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('story', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.LargeBinary(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('story', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
