"""empty message

Revision ID: 25b86e42c640
Revises: ec9fe7a31e28
Create Date: 2024-12-13 14:56:05.982383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25b86e42c640'
down_revision = 'ec9fe7a31e28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('user_share', sa.Float(), nullable=False))
        batch_op.alter_column('link',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bank_account_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('bank_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('bank_account_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('paystack_account_id', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('paystack_account_id')
        batch_op.drop_column('bank_account_type')
        batch_op.drop_column('bank_name')
        batch_op.drop_column('bank_account_number')

    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('link',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.drop_column('user_share')
        batch_op.drop_column('price')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
