"""empty message

Revision ID: 29c677216318
Revises: e850552775c9
Create Date: 2024-12-11 17:45:38.261897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29c677216318'
down_revision = 'e850552775c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('rules', sa.Text(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('profile_picture', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('groups_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'denied', name='membership_status'), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['groups_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('membership')
    op.drop_table('group_members')
    with op.batch_alter_table('join_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('groups_id', sa.String(), nullable=True))
        batch_op.create_foreign_key(None, 'groups', ['groups_id'], ['id'])
        batch_op.drop_column('group_id')

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receiver_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('groups_id', sa.String(), nullable=True))
        batch_op.drop_constraint('message_recipient_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['receiver_id'], ['id'])
        batch_op.create_foreign_key(None, 'groups', ['groups_id'], ['id'])
        batch_op.drop_column('group_id')
        batch_op.drop_column('recipient_id')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('groups_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key(None, 'groups', ['groups_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('groups_id')

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipient_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('group_id', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('message_recipient_id_fkey', 'users', ['recipient_id'], ['id'])
        batch_op.drop_column('groups_id')
        batch_op.drop_column('receiver_id')

    with op.batch_alter_table('join_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_id', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('groups_id')

    op.create_table('group_members',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='group_members_pkey')
    )
    op.create_table('membership',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('group_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='membership_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='membership_pkey')
    )
    op.drop_table('memberships')
    op.drop_table('groups')
    # ### end Alembic commands ###
