"""empty message

Revision ID: 411651ca8144
Revises: 88fe2090f31d
Create Date: 2024-12-21 17:46:49.144437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '411651ca8144'
down_revision = '88fe2090f31d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cofounders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_names', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('occupation', sa.String(length=255), nullable=True))

    with op.batch_alter_table('investors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_names', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('occupation', sa.String(length=255), nullable=True))

    with op.batch_alter_table('startups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_names', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('occupation', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('startups', schema=None) as batch_op:
        batch_op.drop_column('occupation')
        batch_op.drop_column('full_names')

    with op.batch_alter_table('investors', schema=None) as batch_op:
        batch_op.drop_column('occupation')
        batch_op.drop_column('full_names')

    with op.batch_alter_table('cofounders', schema=None) as batch_op:
        batch_op.drop_column('occupation')
        batch_op.drop_column('full_names')

    # ### end Alembic commands ###
