"""empty message

Revision ID: 7316d54b6a76
Revises: 3426884a1fe1
Create Date: 2024-11-29 10:35:32.708415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7316d54b6a76'
down_revision = '3426884a1fe1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('requested_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_request', schema=None) as batch_op:
        batch_op.drop_column('requested_date')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
