"""empty message

Revision ID: 73bf1e46f510
Revises: ff93679bf4c1
Create Date: 2024-12-05 06:09:48.938733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73bf1e46f510'
down_revision = 'ff93679bf4c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('story', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chunk_size', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('story', schema=None) as batch_op:
        batch_op.drop_column('chunk_size')

    # ### end Alembic commands ###
