"""Removed link field from Resource model

Revision ID: 844c635b6042
Revises: 500118773e39
Create Date: 2024-12-21 13:55:40.025663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '844c635b6042'
down_revision = '500118773e39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.drop_column('link')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link', sa.VARCHAR(length=200), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
