"""empty message

Revision ID: 9f07a551e38c
Revises: 161a9cd0a80c
Create Date: 2024-11-27 17:08:25.462378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f07a551e38c'
down_revision = '161a9cd0a80c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dispatch_rider',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('vehicle_type', sa.String(length=50), nullable=False),
    sa.Column('vehicle_number', sa.String(length=50), nullable=False),
    sa.Column('vehicle_model', sa.String(length=100), nullable=False),
    sa.Column('vehicle_color', sa.String(length=50), nullable=False),
    sa.Column('vehicle_image', sa.String(length=200), nullable=True),
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dispatch_rider')
    # ### end Alembic commands ###
